version: "2"

services:
  php_test:
    build:
      context: .
    network_mode: "host"
    volumes:
        - ../../../php-webdriver:/workspace
        - ~/.bash_history_docker:/var/www/.bash_history
        - /etc/timezone:/etc/timezone:ro
        - /etc/localtime:/etc/localtime:ro
    environment:
        - PHP_IDE_CONFIG=serverName=my.local
        - XDEBUG_CONFIG=remote_host=my.local idekey=PHPSTORM









